# Generated by Django 5.2.6 on 2025-10-05 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standard_quantity', models.PositiveIntegerField()),
                ('packaging_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('applicable_products', models.ManyToManyField(related_name='packaging_types', to='products.product')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
            },
        ),
        migrations.CreateModel(
            name='PackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pack_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('packed', 'Packed'), ('in_fg_store', 'In FG Store'), ('dispatched', 'Dispatched')], default='packed', max_length=20)),
                ('qr_code_data', models.TextField()),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='manufacturing.manufacturingorder')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.packagingtype')),
                ('packed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Packed Item',
                'verbose_name_plural': 'Packed Items',
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('delivery_address', models.TextField()),
                ('dispatch_datetime', models.DateTimeField()),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('driver_details', models.CharField(blank=True, max_length=200)),
                ('dispatch_note_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_orders', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='manufacturing.manufacturingorder')),
                ('packed_items', models.ManyToManyField(related_name='dispatch_orders', to='logistics.packeditem')),
            ],
            options={
                'verbose_name': 'Dispatch Order',
                'verbose_name_plural': 'Dispatch Orders',
            },
        ),
    ]
