# Generated by Django 5.2.6 on 2025-09-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('logistics', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='mo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='applicable_products',
            field=models.ManyToManyField(related_name='packaging_types', to='products.product'),
        ),
        migrations.AddField(
            model_name='packeditem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='manufacturing.batch'),
        ),
        migrations.AddField(
            model_name='packeditem',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='packeditem',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.packagingtype'),
        ),
        migrations.AddField(
            model_name='packeditem',
            name='packed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='packed_items',
            field=models.ManyToManyField(related_name='dispatch_orders', to='logistics.packeditem'),
        ),
    ]
