# Generated by Django 5.2.6 on 2025-10-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('manufacturing', '0016_add_outsourcing_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='mo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_dispatch_orders', to='manufacturing.manufacturingorder'),
        ),
    ]
