# Generated by Django 5.2.6 on 2025-09-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20250923_0835'),
        ('manufacturing', '0003_auto_20250923_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packeditem',
            name='batch',
        ),
        migrations.AddField(
            model_name='packeditem',
            name='manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='manufacturing.manufacturingorder'),
        ),
    ]
