# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='processes.process')),
            ],
            options={
                'ordering': ['process', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_code', models.CharField(max_length=255, unique=True)),
                ('sequence_order', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='processes.process')),
                ('subprocess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='processes.subprocess')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('step_code', 'process')},
            },
        ),
        migrations.CreateModel(
            name='WorkCenterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_deadline', models.TimeField(default='09:15:00', help_text='Time by which supervisor should log in (e.g., 9:15 AM)')),
                ('is_active', models.BooleanField(default=True, help_text='Active work center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_supervisor', models.ForeignKey(help_text='Alternate supervisor for this work center', on_delete=django.db.models.deletion.PROTECT, related_name='backup_work_centers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_centers', to=settings.AUTH_USER_MODEL)),
                ('default_supervisor', models.ForeignKey(help_text='Main supervisor assigned to this work center', on_delete=django.db.models.deletion.PROTECT, related_name='default_work_centers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_centers', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.OneToOneField(help_text='Process that serves as work center', on_delete=django.db.models.deletion.CASCADE, related_name='work_center_master', to='processes.process')),
            ],
            options={
                'verbose_name': 'Work Center Master',
                'verbose_name_plural': 'Work Center Masters',
                'ordering': ['work_center__name'],
            },
        ),
        migrations.CreateModel(
            name='DailySupervisorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this status record')),
                ('is_present', models.BooleanField(default=False, help_text='Whether default supervisor logged in before deadline')),
                ('login_time', models.TimeField(blank=True, help_text='Time when default supervisor logged in', null=True)),
                ('check_in_deadline', models.TimeField(help_text='Deadline time for check-in on this date')),
                ('manually_updated', models.BooleanField(default=False, help_text='Whether this record was manually updated by admin')),
                ('manually_updated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_update_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_supervisor', models.ForeignKey(help_text='Active supervisor for this work center today (default or backup)', on_delete=django.db.models.deletion.PROTECT, related_name='daily_active_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('default_supervisor', models.ForeignKey(help_text='Default supervisor for this work center on this date', on_delete=django.db.models.deletion.PROTECT, related_name='daily_default_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('manually_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_updated_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(help_text='Work center for this status', on_delete=django.db.models.deletion.CASCADE, related_name='daily_supervisor_status', to='processes.process')),
            ],
            options={
                'verbose_name': 'Daily Supervisor Status',
                'verbose_name_plural': 'Daily Supervisor Statuses',
                'ordering': ['-date', 'work_center__name'],
                'indexes': [models.Index(fields=['date', 'work_center'], name='processes_d_date_511617_idx'), models.Index(fields=['date', 'is_present'], name='processes_d_date_0f241d_idx')],
                'unique_together': {('date', 'work_center')},
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('spring', 'Spring'), ('press_component', 'PRESS COMPONENT'), ('stamp', 'Stamp')], max_length=20)),
                ('sheet_length', models.DecimalField(blank=True, decimal_places=2, help_text='Whole sheet length in mm', max_digits=10, null=True)),
                ('sheet_breadth', models.DecimalField(blank=True, decimal_places=2, help_text='Whole sheet breadth in mm', max_digits=10, null=True)),
                ('strip_length', models.DecimalField(blank=True, decimal_places=2, help_text='Strip length in mm', max_digits=10, null=True)),
                ('strip_breadth', models.DecimalField(blank=True, decimal_places=2, help_text='Strip breadth in mm', max_digits=10, null=True)),
                ('strip_count', models.IntegerField(blank=True, help_text='Number of strips per sheet', null=True)),
                ('pcs_per_strip', models.IntegerField(blank=True, help_text='Number of pieces per strip', null=True)),
                ('pcs_per_sheet', models.IntegerField(blank=True, help_text='Total pieces per sheet', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial', to_field='material_code')),
                ('process_step', models.ForeignKey(help_text='Specific process step with ordering', on_delete=django.db.models.deletion.CASCADE, to='processes.processstep')),
            ],
            options={
                'ordering': ['product_code', 'type'],
                'unique_together': {('product_code', 'process_step', 'material')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of activity')),
                ('mos_handled', models.PositiveIntegerField(default=0, help_text='Number of MOs handled')),
                ('total_operations', models.PositiveIntegerField(default=0, help_text='Total operations/process executions handled')),
                ('operations_completed', models.PositiveIntegerField(default=0, help_text='Operations completed')),
                ('operations_in_progress', models.PositiveIntegerField(default=0, help_text='Operations in progress')),
                ('total_processing_time_minutes', models.PositiveIntegerField(default=0, help_text='Total processing time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_supervisor', models.ForeignKey(help_text='Supervisor who was active', on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(help_text='Work center', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_activity_logs', to='processes.process')),
            ],
            options={
                'verbose_name': 'Supervisor Activity Log',
                'verbose_name_plural': 'Supervisor Activity Logs',
                'ordering': ['-date', 'work_center__name'],
                'indexes': [models.Index(fields=['date', 'work_center'], name='processes_s_date_6907ad_idx'), models.Index(fields=['date', 'active_supervisor'], name='processes_s_date_537ffd_idx')],
                'unique_together': {('date', 'work_center', 'active_supervisor')},
            },
        ),
    ]
