# Generated by Django 5.2.6 on 2025-09-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('material_types', models.ManyToManyField(related_name='process_templates', to='products.materialtype')),
            ],
            options={
                'verbose_name': 'Process Template',
                'verbose_name_plural': 'Process Templates',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('sequence_order', models.PositiveIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('machine_required', models.BooleanField(default=False)),
                ('operator_required', models.BooleanField(default=True)),
                ('quality_checks', models.JSONField(default=dict)),
                ('acceptable_scrap_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.processtemplate')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['template', 'sequence_order'],
                'unique_together': {('template', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='ProcessStepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('prerequisite', 'Must Complete Before'), ('parallel', 'Can Run Parallel'), ('optional', 'Optional Dependency')], max_length=20)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='processes.processstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='processes.processstep')),
            ],
            options={
                'verbose_name': 'Process Step Dependency',
                'verbose_name_plural': 'Process Step Dependencies',
                'unique_together': {('step', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='ProductProcessMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='processes.processtemplate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_mappings', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Process Mapping',
                'verbose_name_plural': 'Product Process Mappings',
                'unique_together': {('product', 'process_template')},
            },
        ),
    ]
