# Generated by Django 5.2.6 on 2025-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='step_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
