# Generated by Django 5.2.6 on 2025-09-27 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_rawmaterial_product_code_and_more'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial'),
        ),
    ]
