# Generated by Django 5.2.6 on 2025-10-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_deadline', models.TimeField(default='09:15:00', help_text='Time by which supervisor should log in (e.g., 9:15 AM)')),
                ('is_active', models.BooleanField(default=True, help_text='Active work center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_supervisor', models.ForeignKey(help_text='Alternate supervisor for this work center', on_delete=django.db.models.deletion.PROTECT, related_name='backup_work_centers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_centers', to=settings.AUTH_USER_MODEL)),
                ('default_supervisor', models.ForeignKey(help_text='Main supervisor assigned to this work center', on_delete=django.db.models.deletion.PROTECT, related_name='default_work_centers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_centers', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.OneToOneField(help_text='Process that serves as work center', on_delete=django.db.models.deletion.CASCADE, related_name='work_center_master', to='processes.process')),
            ],
            options={
                'verbose_name': 'Work Center Master',
                'verbose_name_plural': 'Work Center Masters',
                'ordering': ['work_center__name'],
            },
        ),
        migrations.CreateModel(
            name='DailySupervisorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this status record')),
                ('is_present', models.BooleanField(default=False, help_text='Whether default supervisor logged in before deadline')),
                ('login_time', models.TimeField(blank=True, help_text='Time when default supervisor logged in', null=True)),
                ('check_in_deadline', models.TimeField(help_text='Deadline time for check-in on this date')),
                ('manually_updated', models.BooleanField(default=False, help_text='Whether this record was manually updated by admin')),
                ('manually_updated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_update_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_supervisor', models.ForeignKey(help_text='Active supervisor for this work center today (default or backup)', on_delete=django.db.models.deletion.PROTECT, related_name='daily_active_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('default_supervisor', models.ForeignKey(help_text='Default supervisor for this work center on this date', on_delete=django.db.models.deletion.PROTECT, related_name='daily_default_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('manually_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_updated_supervisor_status', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(help_text='Work center for this status', on_delete=django.db.models.deletion.CASCADE, related_name='daily_supervisor_status', to='processes.process')),
            ],
            options={
                'verbose_name': 'Daily Supervisor Status',
                'verbose_name_plural': 'Daily Supervisor Statuses',
                'ordering': ['-date', 'work_center__name'],
                'indexes': [models.Index(fields=['date', 'work_center'], name='processes_d_date_511617_idx'), models.Index(fields=['date', 'is_present'], name='processes_d_date_0f241d_idx')],
                'unique_together': {('date', 'work_center')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of activity')),
                ('mos_handled', models.PositiveIntegerField(default=0, help_text='Number of MOs handled')),
                ('total_operations', models.PositiveIntegerField(default=0, help_text='Total operations/process executions handled')),
                ('operations_completed', models.PositiveIntegerField(default=0, help_text='Operations completed')),
                ('operations_in_progress', models.PositiveIntegerField(default=0, help_text='Operations in progress')),
                ('total_processing_time_minutes', models.PositiveIntegerField(default=0, help_text='Total processing time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_supervisor', models.ForeignKey(help_text='Supervisor who was active', on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(help_text='Work center', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_activity_logs', to='processes.process')),
            ],
            options={
                'verbose_name': 'Supervisor Activity Log',
                'verbose_name_plural': 'Supervisor Activity Logs',
                'ordering': ['-date', 'work_center__name'],
                'indexes': [models.Index(fields=['date', 'work_center'], name='processes_s_date_6907ad_idx'), models.Index(fields=['date', 'active_supervisor'], name='processes_s_date_537ffd_idx')],
                'unique_together': {('date', 'work_center', 'active_supervisor')},
            },
        ),
    ]
