# Generated by Django 5.2.6 on 2025-10-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_add_work_center_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='pcs_per_sheet',
            field=models.IntegerField(blank=True, help_text='Total pieces per sheet', null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='pcs_per_strip',
            field=models.IntegerField(blank=True, help_text='Number of pieces per strip', null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='sheet_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Whole sheet breadth in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='sheet_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Whole sheet length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='strip_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strip breadth in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='strip_count',
            field=models.IntegerField(blank=True, help_text='Number of strips per sheet', null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='strip_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strip length in mm', max_digits=10, null=True),
        ),
    ]
