# Generated by Django 5.2.6 on 2025-09-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rawmaterial_material_code'),
        ('processes', '0002_alter_bom_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial', to_field='material_code'),
        ),
    ]
