# Generated by Django 5.2.6 on 2025-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_bom_pcs_per_sheet_bom_pcs_per_strip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='type',
            field=models.CharField(choices=[('spring', 'Spring'), ('press_component', 'PRESS COMPONENT'), ('stamp', 'Stamp')], max_length=20),
        ),
    ]
