# Generated by Django 5.2.6 on 2025-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('inward', 'Inward Receipt'), ('outward', 'Outward Issue'), ('transfer', 'Location Transfer'), ('adjustment', 'Stock Adjustment'), ('consumption', 'Process Consumption'), ('production', 'Process Output'), ('scrap', 'Scrap Generation'), ('return', 'Return to Stock')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Idempotency key for safe retries. Ensures no duplicate transaction on retries.', max_length=64, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('reference_type', models.CharField(blank=True, choices=[('mo', 'Manufacturing Order'), ('po', 'Purchase Order'), ('process', 'Process Execution'), ('adjustment', 'Stock Adjustment')], max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_name', models.CharField(choices=[('rm_store', 'Raw Material Store'), ('coiling', 'Coiling'), ('forming', 'Forming'), ('tempering', 'Tempering'), ('coating', 'Coating'), ('blanking', 'Blanking'), ('piercing', 'Piercing'), ('deburring', 'Deburring'), ('ironing', 'Ironing'), ('champering', 'Champering'), ('bending', 'Bending'), ('plating', 'Plating'), ('blue_coating', 'Blue Coating'), ('bush_assembly', 'Bush Assembly'), ('riveting', 'Riveting'), ('remar', 'Remar'), ('brass_welding', 'Brass Welding'), ('grinding_buffing', 'Grinding & Buffing'), ('blacking', 'Blacking'), ('phosphating', 'Phosphating'), ('final_inspection', 'Final Inspection'), ('packing_zone', 'Packing Zone'), ('fg', 'FG Store'), ('dispatched', 'Dispatched')], default='rm_store', max_length=20)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(choices=[('spring', 'Spring Steel'), ('stain', 'Stainless Steel'), ('ms', 'Mild Steel')], max_length=20)),
                ('material_type', models.CharField(choices=[('coil', 'Coil'), ('sheet', 'Sheet')], max_length=20)),
                ('grade', models.CharField(max_length=50)),
                ('wire_diameter_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Coil', max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in KG for Coil type', max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Sheet', max_digits=8, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for Sheet type kg', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_name', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='RMStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coil', 'Coil'), ('sheet', 'Sheet')], max_length=5)),
                ('current_quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Stock Balance',
                'verbose_name_plural': 'Inventory Stock Balances',
            },
        ),
    ]
