# Generated by Django 5.2.6 on 2025-11-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRMReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grm_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('truck_number', models.CharField(blank=True, help_text='Truck/Van number', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Receipt'), ('partial', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_items_received', models.DecimalField(decimal_places=2, default=0, help_text='Total items/weight received (in kg for weight-based, count for count-based)', max_digits=10)),
                ('total_items_expected', models.DecimalField(decimal_places=2, default=0, help_text='Total items/weight expected (in kg for weight-based, count for count-based)', max_digits=10)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('quality_check_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GRM Receipt',
                'verbose_name_plural': 'GRM Receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='HandoverIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('incorrect_weight', 'Incorrect Weight'), ('damaged_material', 'Damaged Material'), ('wrong_material', 'Wrong Material')], help_text='Type of issue reported', max_length=20)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Actual weight found (if different from expected)', max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the issue')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved')),
            ],
            options={
                'verbose_name': 'Handover Issue',
                'verbose_name_plural': 'Handover Issues',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.CharField(help_text='Heat number from supplier', max_length=50)),
                ('coils_received', models.PositiveIntegerField(default=0, help_text='Number of coils received for this heat number')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Total weight in KG for this heat number', max_digits=10, null=True)),
                ('sheets_received', models.PositiveIntegerField(default=0, help_text='Number of sheets received (for sheet materials)')),
                ('test_certificate_date', models.DateField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list, help_text='List of individual coil/sheet items with number and weight')),
                ('is_available', models.BooleanField(default=True, help_text='Is this heat number still available for use')),
                ('consumed_quantity_kg', models.DecimalField(decimal_places=3, default=0, help_text='Quantity consumed from this heat number', max_digits=10)),
                ('handover_status', models.CharField(choices=[('pending_handover', 'Pending Handover'), ('verified', 'Verified'), ('issue_reported', 'Issue Reported')], default='pending_handover', help_text='Status of handover verification to Coiling department', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the handover was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heat Number',
                'verbose_name_plural': 'Heat Numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('inward', 'Inward Receipt'), ('outward', 'Outward Issue'), ('transfer', 'Location Transfer'), ('adjustment', 'Stock Adjustment'), ('consumption', 'Process Consumption'), ('production', 'Process Output'), ('scrap', 'Scrap Generation'), ('return', 'Return to Stock')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Idempotency key for safe retries. Ensures no duplicate transaction on retries.', max_length=64, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('reference_type', models.CharField(blank=True, choices=[('mo', 'Manufacturing Order'), ('po', 'Purchase Order'), ('process', 'Process Execution'), ('adjustment', 'Stock Adjustment')], max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactionHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, help_text='Quantity in KG for this transaction', max_digits=10)),
                ('coils_count', models.PositiveIntegerField(default=0, help_text='Number of coils involved (for coil materials)')),
                ('sheets_count', models.PositiveIntegerField(default=0, help_text='Number of sheets involved (for sheet materials)')),
                ('grm_number', models.CharField(help_text='GRM number for traceability', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory Transaction Heat',
                'verbose_name_plural': 'Inventory Transactions Heat',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_name', models.CharField(choices=[('rm_store', 'Raw Material Store'), ('coiling', 'Coiling'), ('forming', 'Forming'), ('tempering', 'Tempering'), ('coating', 'Coating'), ('blanking', 'Blanking'), ('piercing', 'Piercing'), ('deburring', 'Deburring'), ('ironing', 'Ironing'), ('champering', 'Champering'), ('bending', 'Bending'), ('plating', 'Plating'), ('blue_coating', 'Blue Coating'), ('bush_assembly', 'Bush Assembly'), ('riveting', 'Riveting'), ('remar', 'Remar'), ('brass_welding', 'Brass Welding'), ('grinding_buffing', 'Grinding & Buffing'), ('blacking', 'Blacking'), ('phosphating', 'Phosphating'), ('final_inspection', 'Final Inspection'), ('packing_zone', 'Packing Zone'), ('fg', 'FG Store'), ('dispatched', 'Dispatched')], default='rm_store', max_length=20)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Current quantity at this location', max_digits=10)),
                ('last_moved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Location',
                'verbose_name_plural': 'Product Locations',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(help_text='Unique identifier for the raw material', max_length=50, unique=True)),
                ('material_name', models.CharField(help_text='Complete material name from CSV', max_length=100)),
                ('material_type', models.CharField(choices=[('coil', 'Coil'), ('sheet', 'Sheet')], max_length=20)),
                ('grade', models.CharField(max_length=50)),
                ('finishing', models.CharField(blank=True, choices=[('soap_coated', 'Soap Coated'), ('bright', 'BRIGHT')], max_length=20, null=True)),
                ('wire_diameter_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Coil', max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in KG for Coil type', max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Sheet', max_digits=8, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Length in mm (for sheet type materials)', max_digits=10, null=True)),
                ('breadth_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Breadth in mm (for sheet type materials)', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Number of sheets (for sheet type materials)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_name', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='RMReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(editable=False, help_text='Auto-generated return ID', max_length=50, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, help_text='Quantity returned in KG', max_digits=10)),
                ('return_reason', models.TextField(help_text='Reason for returning the raw material')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('disposition', models.CharField(choices=[('pending', 'Pending Action'), ('return_to_vendor', 'Return to Vendor'), ('scrap', 'Scrap')], default='pending', help_text='Action taken by RM Store', max_length=20)),
                ('disposition_notes', models.TextField(blank=True, help_text='Notes about the disposition decision')),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RM Return',
                'verbose_name_plural': 'RM Returns',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='RMStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(decimal_places=3, help_text='Available quantity in KG or pieces', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RM Stock Balance',
                'verbose_name_plural': 'RM Stock Balances',
            },
        ),
        migrations.CreateModel(
            name='RMStockBalanceHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_available_quantity_kg', models.DecimalField(decimal_places=3, default=0, help_text='Total available quantity across all heat numbers', max_digits=10)),
                ('total_coils_available', models.PositiveIntegerField(default=0, help_text='Total coils available across all heat numbers')),
                ('total_sheets_available', models.PositiveIntegerField(default=0, help_text='Total sheets available across all heat numbers')),
                ('active_heat_numbers_count', models.PositiveIntegerField(default=0, help_text='Number of active heat numbers with available stock')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RM Stock Balance (Heat Tracked)',
                'verbose_name_plural': 'RM Stock Balances (Heat Tracked)',
            },
        ),
    ]
