# Generated by Django 5.2.6 on 2025-10-05 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_name', models.CharField(choices=[('rm_store', 'Raw Material Store'), ('coiling', 'Coiling'), ('forming', 'Forming'), ('tempering', 'Tempering'), ('coating', 'Coating'), ('blanking', 'Blanking'), ('piercing', 'Piercing'), ('deburring', 'Deburring'), ('ironing', 'Ironing'), ('champering', 'Champering'), ('bending', 'Bending'), ('plating', 'Plating'), ('blue_coating', 'Blue Coating'), ('bush_assembly', 'Bush Assembly'), ('riveting', 'Riveting'), ('remar', 'Remar'), ('brass_welding', 'Brass Welding'), ('grinding_buffing', 'Grinding & Buffing'), ('blacking', 'Blacking'), ('phosphating', 'Phosphating'), ('final_inspection', 'Final Inspection'), ('packing_zone', 'Packing Zone'), ('fg', 'FG Store'), ('dispatched', 'Dispatched')], default='rm_store', max_length=20)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(help_text='Unique identifier for the raw material', max_length=50, unique=True)),
                ('material_name', models.CharField(help_text='Complete material name from CSV', max_length=100)),
                ('material_type', models.CharField(choices=[('coil', 'Coil'), ('sheet', 'Sheet')], max_length=20)),
                ('grade', models.CharField(max_length=50)),
                ('finishing', models.CharField(blank=True, choices=[('soap_coated', 'Soap Coated'), ('bright', 'BRIGHT')], max_length=20, null=True)),
                ('wire_diameter_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Coil', max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in KG for Coil type', max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Required if material type is Sheet', max_digits=8, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity for Sheet type kg', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_name', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='RMStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(decimal_places=3, help_text='Available quantity in KG or pieces', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RM Stock Balance',
                'verbose_name_plural': 'RM Stock Balances',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('inward', 'Inward Receipt'), ('outward', 'Outward Issue'), ('transfer', 'Location Transfer'), ('adjustment', 'Stock Adjustment'), ('consumption', 'Process Consumption'), ('production', 'Process Output'), ('scrap', 'Scrap Generation'), ('return', 'Return to Stock')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Idempotency key for safe retries. Ensures no duplicate transaction on retries.', max_length=64, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('reference_type', models.CharField(blank=True, choices=[('mo', 'Manufacturing Order'), ('po', 'Purchase Order'), ('process', 'Process Execution'), ('adjustment', 'Stock Adjustment')], max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
            },
        ),
    ]
