# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grmreceipt',
            name='purchase_order',
            field=models.ForeignKey(help_text='Purchase Order this GRM is for', on_delete=django.db.models.deletion.PROTECT, related_name='grm_receipts', to='manufacturing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grmreceipt',
            name='quality_check_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_grms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grmreceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grm_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handoverissue',
            name='reported_by',
            field=models.ForeignKey(help_text='User who reported the issue', on_delete=django.db.models.deletion.PROTECT, related_name='reported_handover_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handoverissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_handover_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatnumber',
            name='grm_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_numbers', to='inventory.grmreceipt'),
        ),
        migrations.AddField(
            model_name='heatnumber',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the handover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_heat_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handoverissue',
            name='heat_number',
            field=models.ForeignKey(help_text='Heat number for which issue was reported', on_delete=django.db.models.deletion.CASCADE, related_name='handover_issues', to='inventory.heatnumber'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorytransactionheat',
            name='heat_number',
            field=models.ForeignKey(help_text='Specific heat number involved in this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.heatnumber'),
        ),
        migrations.AddField(
            model_name='inventorytransactionheat',
            name='inventory_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heat_transaction', to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='manufacturing.batch'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='last_moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='products.product'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='heatnumber',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heat_numbers', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='batch',
            field=models.ForeignKey(help_text='Batch that returned this material', on_delete=django.db.models.deletion.CASCADE, related_name='rm_returns', to='manufacturing.batch'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='disposed_by',
            field=models.ForeignKey(blank=True, help_text='RM Store user who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_returns_disposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='heat_number',
            field=models.ForeignKey(blank=True, help_text='Heat number of the returned material (if tracked)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.heatnumber'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='manufacturing_order',
            field=models.ForeignKey(help_text='Manufacturing Order associated with this return', on_delete=django.db.models.deletion.CASCADE, related_name='rm_returns', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='raw_material',
            field=models.ForeignKey(help_text='Raw material being returned', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='return_transaction',
            field=models.ForeignKey(blank=True, help_text='Inventory transaction created for this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_return_records', to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='returned_by',
            field=models.ForeignKey(help_text='Supervisor who returned the material', on_delete=django.db.models.deletion.PROTECT, related_name='rm_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmreturn',
            name='returned_from_location',
            field=models.ForeignKey(help_text='Location/process from which material was returned', on_delete=django.db.models.deletion.PROTECT, related_name='rm_returns_from', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='rmstockbalance',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rmstockbalanceheat',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='rmstockbalanceheat',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_stock_balances', to='inventory.rawmaterial'),
        ),
        migrations.AddIndex(
            model_name='grmreceipt',
            index=models.Index(fields=['grm_number'], name='inventory_g_grm_num_fb00f4_idx'),
        ),
        migrations.AddIndex(
            model_name='grmreceipt',
            index=models.Index(fields=['receipt_date'], name='inventory_g_receipt_e26013_idx'),
        ),
        migrations.AddIndex(
            model_name='grmreceipt',
            index=models.Index(fields=['status'], name='inventory_g_status_f00651_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverissue',
            index=models.Index(fields=['heat_number'], name='inventory_h_heat_nu_40448c_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverissue',
            index=models.Index(fields=['reported_at'], name='inventory_h_reporte_f4b087_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverissue',
            index=models.Index(fields=['is_resolved'], name='inventory_h_is_reso_735905_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransactionheat',
            index=models.Index(fields=['heat_number'], name='inventory_i_heat_nu_3efd06_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransactionheat',
            index=models.Index(fields=['grm_number'], name='inventory_i_grm_num_c1f9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_datetime'], name='inventory_i_transac_f335e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'location_to'], name='inventory_i_product_7ae9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='productlocation',
            index=models.Index(fields=['current_location'], name='inventory_p_current_21eba1_idx'),
        ),
        migrations.AddIndex(
            model_name='productlocation',
            index=models.Index(fields=['last_moved_at'], name='inventory_p_last_mo_70b257_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', True), ('product__isnull', False), ('raw_material__isnull', True)), models.Q(('batch__isnull', True), ('product__isnull', True), ('raw_material__isnull', False)), models.Q(('batch__isnull', False), ('product__isnull', True), ('raw_material__isnull', True)), _connector='OR'), name='only_one_item_type'),
        ),
        migrations.AddIndex(
            model_name='heatnumber',
            index=models.Index(fields=['heat_number'], name='inventory_h_heat_nu_4912d1_idx'),
        ),
        migrations.AddIndex(
            model_name='heatnumber',
            index=models.Index(fields=['grm_receipt', 'raw_material'], name='inventory_h_grm_rec_af7842_idx'),
        ),
        migrations.AddIndex(
            model_name='heatnumber',
            index=models.Index(fields=['is_available'], name='inventory_h_is_avai_3efe22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heatnumber',
            unique_together={('heat_number', 'grm_receipt', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='rmreturn',
            index=models.Index(fields=['batch'], name='inventory_r_batch_i_19758a_idx'),
        ),
        migrations.AddIndex(
            model_name='rmreturn',
            index=models.Index(fields=['manufacturing_order'], name='inventory_r_manufac_b82e00_idx'),
        ),
        migrations.AddIndex(
            model_name='rmreturn',
            index=models.Index(fields=['disposition'], name='inventory_r_disposi_f6f9de_idx'),
        ),
        migrations.AddIndex(
            model_name='rmreturn',
            index=models.Index(fields=['returned_at'], name='inventory_r_returne_1e2bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='rmreturn',
            index=models.Index(fields=['return_id'], name='inventory_r_return__53334a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rmstockbalance',
            unique_together={('raw_material',)},
        ),
        migrations.AlterUniqueTogether(
            name='rmstockbalanceheat',
            unique_together={('raw_material',)},
        ),
    ]
