# Generated by Django 5.2.6 on 2025-10-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='quantity',
        ),
    ]
