# Generated by Django 5.2.6 on 2025-11-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmreturn',
            name='received_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual quantity received by RM Store when processing', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rmreturn',
            name='disposition',
            field=models.CharField(choices=[('pending', 'Pending Action'), ('return_to_rm', 'Return to RM'), ('return_to_vendor', 'Return to Vendor'), ('scrap', 'Scrap')], default='pending', help_text='Action taken by RM Store', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmreturn',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, help_text='Quantity returned by Supervisor in KG', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rmreturn',
            name='return_reason',
            field=models.CharField(choices=[('received_wrong_rm', 'Received Wrong RM'), ('enough_qty_reached', 'Enough Qty Reached'), ('defect_in_quality', 'Defect in Quality')], help_text='Reason for returning the raw material', max_length=30),
        ),
    ]
