# Generated by Django 5.2.6 on 2025-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_rawmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Breadth in mm (for sheet type materials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Length in mm (for sheet type materials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sheets (for sheet type materials)', null=True),
        ),
    ]
