# Generated by Django 5.2.6 on 2025-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorytransaction_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='product_code',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='finishing',
            field=models.CharField(blank=True, choices=[('soap_coated', 'Soap Coated'), ('bright', 'BRIGHT')], max_length=20, null=True),
        ),
    ]
