# Generated by Django 5.2.6 on 2025-10-07 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawmaterial_breadth_mm_rawmaterial_length_mm_and_more'),
        ('manufacturing', '0008_moprocessexecution_assigned_supervisor'),
        ('products', '0004_update_sheet_calculation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Current quantity at this location', max_digits=10)),
                ('last_moved_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='manufacturing.batch')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to='inventory.location')),
                ('last_moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytransaction')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='products.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Product Location',
                'verbose_name_plural': 'Product Locations',
                'indexes': [models.Index(fields=['current_location'], name='inventory_p_current_21eba1_idx'), models.Index(fields=['last_moved_at'], name='inventory_p_last_mo_70b257_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', True), ('product__isnull', False), ('raw_material__isnull', True)), models.Q(('batch__isnull', True), ('product__isnull', True), ('raw_material__isnull', False)), models.Q(('batch__isnull', False), ('product__isnull', True), ('raw_material__isnull', True)), _connector='OR'), name='only_one_item_type')],
            },
        ),
    ]
