# Generated by Django 5.2.6 on 2025-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_rawmaterial_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='material_code',
            field=models.CharField(blank=True, help_text='Unique identifier for the raw material', max_length=50, null=True),
        ),
    ]
