# Generated by Django 5.2.6 on 2025-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_grm_heat_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grmreceipt',
            new_name='inventory_g_grm_num_fb00f4_idx',
            old_name='inventory_grmreceipt_grm_number_idx',
        ),
        migrations.RenameIndex(
            model_name='grmreceipt',
            new_name='inventory_g_receipt_e26013_idx',
            old_name='inventory_grmreceipt_receipt_date_idx',
        ),
        migrations.RenameIndex(
            model_name='grmreceipt',
            new_name='inventory_g_status_f00651_idx',
            old_name='inventory_grmreceipt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='heatnumber',
            new_name='inventory_h_heat_nu_4912d1_idx',
            old_name='inventory_heatnumber_heat_number_idx',
        ),
        migrations.RenameIndex(
            model_name='heatnumber',
            new_name='inventory_h_grm_rec_af7842_idx',
            old_name='inventory_heatnumber_grm_raw_idx',
        ),
        migrations.RenameIndex(
            model_name='heatnumber',
            new_name='inventory_h_is_avai_3efe22_idx',
            old_name='inventory_heatnumber_is_available_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransactionheat',
            new_name='inventory_i_heat_nu_3efd06_idx',
            old_name='inventory_inventorytransactionheat_heat_number_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransactionheat',
            new_name='inventory_i_grm_num_c1f9e7_idx',
            old_name='inventory_inventorytransactionheat_grm_number_idx',
        ),
    ]
