# Generated by Django 5.2.6 on 2025-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_populate_material_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_code',
            field=models.CharField(help_text='Unique identifier for the raw material', max_length=50, unique=True),
        ),
    ]
