# Generated by Django 5.2.6 on 2025-10-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_inventory_grmreceipt_grm_number_idx_inventory_g_grm_num_fb00f4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grmreceipt',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='grmreceipt',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='heatnumber',
            name='quality_certificate_number',
        ),
        migrations.RemoveField(
            model_name='heatnumber',
            name='rack_number',
        ),
        migrations.RemoveField(
            model_name='heatnumber',
            name='shelf_number',
        ),
        migrations.RemoveField(
            model_name='heatnumber',
            name='storage_location',
        ),
    ]
