# Generated by Django 5.2.6 on 2025-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_grmreceipt_driver_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatnumber',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total weight in KG for this heat number', max_digits=10, null=True),
        ),
    ]
