# Generated by Django 5.2.6 on 2025-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rawmaterial_material_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_name',
            field=models.CharField(help_text='Complete material name from CSV', max_length=100),
        ),
    ]
