# Generated by Django 5.2.6 on 2025-10-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_rawmaterial_material_name'),
        ('products', '0005_alter_product_internal_product_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rmstockbalance',
            unique_together={('product',)},
        ),
        migrations.RemoveField(
            model_name='rmstockbalance',
            name='current_quantity',
        ),
        migrations.RemoveField(
            model_name='rmstockbalance',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='rmstockbalance',
            name='type',
        ),
    ]
