# Generated by Django 5.2.6 on 2025-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_heatnumber_total_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatnumber',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of individual coil/sheet items with number and weight'),
        ),
    ]
