# Generated by Django 5.2.6 on 2025-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_heatnumber_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grmreceipt',
            name='total_items_expected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total items/weight expected (in kg for weight-based, count for count-based)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='grmreceipt',
            name='total_items_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total items/weight received (in kg for weight-based, count for count-based)', max_digits=10),
        ),
    ]
