# Generated by Django 5.2.6 on 2025-11-07 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_names', models.JSONField(default=list, help_text='List of process names to be monitored')),
                ('frequency_hours', models.IntegerField(help_text='Hours between QC uploads (e.g., 1, 2, or 3 hours)', validators=[django.core.validators.MinValueValidator(1)])),
                ('shift_start_time', models.TimeField(help_text='Shift start time')),
                ('shift_end_time', models.TimeField(help_text='Shift end time')),
                ('shift_type', models.CharField(blank=True, choices=[('I', '9AM-5PM (Shift I)'), ('II', '5PM-2AM (Shift II)'), ('III', '2AM-9AM (Shift III)')], help_text='Shift type (I, II, III)', max_length=10, null=True)),
                ('start_date', models.DateField(help_text='Duty start date')),
                ('end_date', models.DateField(help_text='Duty end date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Production Head who created this duty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patrol_duties', to=settings.AUTH_USER_MODEL)),
                ('patrol_user', models.ForeignKey(help_text='Patrol user assigned to this duty', on_delete=django.db.models.deletion.CASCADE, related_name='patrol_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrol Duty',
                'verbose_name_plural': 'Patrol Duties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(help_text='Process being checked', max_length=100)),
                ('scheduled_date', models.DateField(help_text='Date for this QC check')),
                ('scheduled_time', models.TimeField(help_text='Scheduled time slot')),
                ('qc_image', models.ImageField(blank=True, help_text='QC sheet image', null=True, upload_to='patrol_qc_images/%Y/%m/%d/')),
                ('upload_timestamp', models.DateTimeField(blank=True, help_text='Actual upload time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('submitted', 'Submitted'), ('missed', 'Missed'), ('reuploaded', 'Reuploaded')], default='pending', max_length=20)),
                ('patrol_remarks', models.TextField(blank=True, help_text='Patrol user remarks (e.g., "All readings normal")', null=True)),
                ('is_reuploaded', models.BooleanField(default=False)),
                ('first_upload_time', models.DateTimeField(blank=True, null=True)),
                ('reupload_deadline', models.DateTimeField(blank=True, help_text='10 minutes after first upload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='patrol.patrolduty')),
            ],
            options={
                'verbose_name': 'Patrol Upload',
                'verbose_name_plural': 'Patrol Uploads',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PatrolAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('duty_assigned', 'Duty Assigned'), ('duty_ending_4hr', 'Duty Ending in 4 Hours'), ('duty_ending_8hr', 'Duty Ending in 8 Hours'), ('upload_missed', 'Upload Missed'), ('duty_completed', 'Duty Completed')], max_length=50)),
                ('message', models.TextField(help_text='Alert message')),
                ('is_read', models.BooleanField(default=False)),
                ('is_action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who should receive this alert', on_delete=django.db.models.deletion.CASCADE, related_name='patrol_alerts', to=settings.AUTH_USER_MODEL)),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patrol.patrolduty')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patrol.patrolupload')),
            ],
            options={
                'verbose_name': 'Patrol Alert',
                'verbose_name_plural': 'Patrol Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patrolduty',
            index=models.Index(fields=['patrol_user', 'status'], name='patrol_patr_patrol__02f286_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolduty',
            index=models.Index(fields=['start_date', 'end_date'], name='patrol_patr_start_d_2e8b47_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolupload',
            index=models.Index(fields=['duty', 'status'], name='patrol_patr_duty_id_5b8dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolupload',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='patrol_patr_schedul_e7e41a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patrolupload',
            unique_together={('duty', 'process_name', 'scheduled_date', 'scheduled_time')},
        ),
        migrations.AddIndex(
            model_name='patrolalert',
            index=models.Index(fields=['recipient', 'is_read'], name='patrol_patr_recipie_d0a2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='patrol_patr_alert_t_837877_idx'),
        ),
    ]
