# Generated by Django 5.2.6 on 2025-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('production_head', 'Production Head'), ('supervisor', 'Supervisor'), ('rm_store', 'RM Store'), ('fg_store', 'FG Store'), ('patrol', 'Patrol')], max_length=50, unique=True),
        ),
    ]
