# Generated by Django 5.2.6 on 2025-09-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['hierarchy_level'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.IntegerField(default=5, help_text='Lower number = higher authority'),
        ),
        migrations.AddField(
            model_name='role',
            name='restricted_departments',
            field=models.JSONField(default=list, help_text='Departments this role can access'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_ip_ranges',
            field=models.JSONField(default=list, help_text='Allowed IP ranges for network restriction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_engaged',
            field=models.BooleanField(default=False, help_text='Currently assigned to a process'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(blank=True, choices=[('I', '9AM-5PM (Shift I)'), ('II', '5PM-2AM (Shift II)'), ('III', '2AM-9AM (Shift III)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('store_manager', 'Store Manager'), ('operator', 'Operator')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('rm_store', 'RM Store'), ('coiling', 'Coiling'), ('tempering', 'Tempering'), ('plating', 'Plating'), ('packing', 'Packing'), ('fg_store', 'FG Store'), ('quality', 'Quality Control'), ('maintenance', 'Maintenance'), ('admin', 'Administration')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Session',
                'verbose_name_plural': 'Login Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='OperatorEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('process_step', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_id', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_engagement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Engagement',
                'verbose_name_plural': 'Operator Engagements',
            },
        ),
        migrations.CreateModel(
            name='ProcessSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_names', models.JSONField(default=list, help_text='List of process names this supervisor handles')),
                ('department', models.CharField(choices=[('rm_store', 'RM Store'), ('coiling', 'Coiling'), ('tempering', 'Tempering'), ('plating', 'Plating'), ('packing', 'Packing'), ('fg_store', 'FG Store'), ('quality', 'Quality Control'), ('maintenance', 'Maintenance'), ('admin', 'Administration')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_supervisor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Supervisor',
                'verbose_name_plural': 'Process Supervisors',
                'unique_together': {('supervisor', 'department')},
            },
        ),
    ]
