# Generated by Django 5.2.6 on 2025-09-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('production_head', 'Production Head'), ('supervisor', 'Supervisor'), ('rm_store', 'RM Store'), ('fg_store', 'FG Store')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
