# Generated by Django 5.2.6 on 2025-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_role_name_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='restricted_departments',
            field=models.JSONField(blank=True, default=list, help_text='Departments this role can access', null=True),
        ),
    ]
