# Generated by Django 5.2.6 on 2025-09-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('input_quantity', models.PositiveIntegerField()),
                ('output_ok', models.PositiveIntegerField(default=0)),
                ('output_rework', models.PositiveIntegerField(default=0)),
                ('output_scrap', models.PositiveIntegerField(default=0)),
                ('process_parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('quality_check_passed', models.BooleanField(blank=True, null=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch Process Execution',
                'verbose_name_plural': 'Batch Process Executions',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_id', models.CharField(max_length=20, unique=True)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('planned_start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('I', '9AM-5PM'), ('II', '5PM-2AM'), ('III', '2AM-9AM')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('customer_order_reference', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manufacturing Order',
                'verbose_name_plural': 'Manufacturing Orders',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20, unique=True)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('actual_quantity_started', models.PositiveIntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('rm_allocated', 'Raw Material Allocated'), ('in_process', 'In Process'), ('quality_check', 'Quality Check'), ('completed', 'Completed'), ('packed', 'Packed'), ('dispatched', 'Dispatched')], default='created', max_length=20)),
                ('total_processing_time_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_process_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.processstep')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
