# Generated by Django 5.2.6 on 2025-11-02 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalrmrequest',
            name='reason',
            field=models.TextField(help_text='Reason for requesting additional RM'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='stopped_at',
            field=models.DateTimeField(blank=True, help_text='When this MO was stopped', null=True),
        ),
        migrations.AlterField(
            model_name='motransactionhistory',
            name='description',
            field=models.TextField(help_text='Human-readable description'),
        ),
        migrations.AlterField(
            model_name='motransactionhistory',
            name='details',
            field=models.JSONField(default=dict, help_text='Detailed transaction data'),
        ),
        migrations.AlterField(
            model_name='motransactionhistory',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='potransactionhistory',
            name='description',
            field=models.TextField(help_text='Human-readable description'),
        ),
        migrations.AlterField(
            model_name='potransactionhistory',
            name='details',
            field=models.JSONField(default=dict, help_text='Detailed transaction data'),
        ),
        migrations.AlterField(
            model_name='potransactionhistory',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction', max_length=50),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['mo_id'], name='manufacturi_mo_id_7cdb82_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['status', 'priority'], name='manufacturi_status_b058f5_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['created_at'], name='manufacturi_created_9cd214_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_id'], name='manufacturi_po_id_4309e2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='manufacturi_status_cdc996_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='manufacturi_created_e0f9d3_idx'),
        ),
    ]
