# Generated by Django 5.2.6 on 2025-10-05 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='assigned_rm_store',
            field=models.ForeignKey(blank=True, help_text='RM Store user to verify and allocate raw materials', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rm_store_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rm_allocated', 'RM Allocated'), ('mo_approved', 'MO Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='on_hold', max_length=20),
        ),
    ]
