# Generated by Django 5.2.6 on 2025-09-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('processes', '0001_initial'),
        ('products', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessexecution',
            name='assigned_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.machine'),
        ),
        migrations.AddField(
            model_name='batchprocessexecution',
            name='assigned_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchprocessexecution',
            name='assigned_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchprocessexecution',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to='manufacturing.batch'),
        ),
        migrations.AddField(
            model_name='batchprocessexecution',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.processstep'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='assigned_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='products.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='mo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='manufacturing.manufacturingorder'),
        ),
    ]
