# Generated by Django 5.2.6 on 2025-10-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_manufacturingorder_assigned_rm_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='gm_approved_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_created_at',
            new_name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gm_approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rm_released_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual RM released by RM Store Manager (in kg or sheets)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='scrap_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected scrap percentage (optional, can be predicted from previous MOs)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='tolerance_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Tolerance percentage for RM loss during process (e.g., 2.00 for ±2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_po_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_po_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='on_hold', max_length=20),
        ),
    ]
