# Generated by Django 5.2.6 on 2025-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_rename_gm_approved_at_purchaseorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='excess_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Excess pieces due to sheet constraints', null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='sheets_required',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sheets required (for sheet-based products)', null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='total_pieces_from_sheets',
            field=models.PositiveIntegerField(blank=True, help_text='Total pieces that will be produced from sheets', null=True),
        ),
    ]
