# Generated by Django 5.2.6 on 2025-09-23 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorytransaction_batch_and_more'),
        ('manufacturing', '0003_auto_20250923_0835'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='current_process_step',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='mo',
        ),
        migrations.RemoveField(
            model_name='batchprocessexecution',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchprocessexecution',
            name='assigned_machine',
        ),
        migrations.RemoveField(
            model_name='batchprocessexecution',
            name='assigned_operator',
        ),
        migrations.RemoveField(
            model_name='batchprocessexecution',
            name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='batchprocessexecution',
            name='process_step',
        ),
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Manufacturing Order', 'verbose_name_plural': 'Manufacturing Orders'},
        ),
        migrations.RenameField(
            model_name='manufacturingorder',
            old_name='product',
            new_name='product_code',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='finishing',
            field=models.CharField(blank=True, help_text='Material finishing details', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='gm_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='gm_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_approved_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='grade',
            field=models.CharField(blank=True, help_text='Auto-filled material grade', max_length=50),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='loose_fg_stock',
            field=models.PositiveIntegerField(default=0, help_text='Available finished goods stock'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='manufacturer_brand',
            field=models.CharField(blank=True, help_text='Material manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='material_name',
            field=models.CharField(blank=True, help_text='Auto-filled from product', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='material_type',
            field=models.CharField(blank=True, help_text='Auto-filled: Coil/Sheet', max_length=20),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product_type',
            field=models.CharField(blank=True, help_text='Auto-filled: Spring/Stamping Part', max_length=50),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity to manufacture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rm_allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rm_allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocated_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rm_required_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Raw material required in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Auto-filled for sheet materials', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='wire_diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Auto-filled for coil materials', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='assigned_supervisor',
            field=models.ForeignKey(help_text='Supervisor allocates operator', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='mo_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('gm_approved', 'GM Approved'), ('rm_allocated', 'RM Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='MOStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'MO Status History',
                'verbose_name_plural': 'MO Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('material_type', models.CharField(blank=True, choices=[('coil', 'Coil'), ('sheet', 'Sheet')], max_length=20)),
                ('material_auto', models.CharField(blank=True, help_text='Auto-filled', max_length=100)),
                ('grade_auto', models.CharField(blank=True, help_text='Auto-filled', max_length=50)),
                ('wire_diameter_mm_auto', models.DecimalField(blank=True, decimal_places=3, help_text='Auto-filled for coil', max_digits=8, null=True)),
                ('finishing_auto', models.CharField(blank=True, help_text='Auto-filled finishing', max_length=100)),
                ('manufacturer_brand_auto', models.CharField(blank=True, help_text='Auto-filled manufacturer', max_length=100)),
                ('kg_auto', models.DecimalField(blank=True, decimal_places=3, help_text='Auto-filled weight', max_digits=10, null=True)),
                ('thickness_mm_auto', models.DecimalField(blank=True, decimal_places=3, help_text='Auto-filled for sheet', max_digits=8, null=True)),
                ('sheet_roll_auto', models.CharField(blank=True, help_text='Auto-filled sheet/roll info', max_length=50)),
                ('qty_sheets_auto', models.PositiveIntegerField(blank=True, help_text='Auto-filled number of sheets', null=True)),
                ('vendor_address_auto', models.TextField(blank=True, help_text='Auto-filled from vendor')),
                ('gst_no_auto', models.CharField(blank=True, help_text='Auto-filled from vendor', max_length=15)),
                ('mob_no_auto', models.CharField(blank=True, help_text='Auto-filled from vendor', max_length=17)),
                ('expected_date', models.DateField(help_text='Expected delivery date')),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity to order')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('gm_approved', 'GM Approved'), ('gm_created_po', 'GM Created PO'), ('vendor_confirmed', 'Vendor Confirmed'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('gm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_po_orders', to=settings.AUTH_USER_MODEL)),
                ('gm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_approved_po_orders', to=settings.AUTH_USER_MODEL)),
                ('po_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_created_orders', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_po_orders', to=settings.AUTH_USER_MODEL)),
                ('rm_code', models.ForeignKey(help_text='Select from dropdown - auto fills other details', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.rawmaterial')),
                ('vendor_name', models.ForeignKey(help_text='Only show vendors who have this material', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='third_party.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='manufacturing.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Status History',
                'verbose_name_plural': 'PO Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
