# Generated by Django 5.2.6 on 2025-09-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorytransaction_batch_and_more'),
        ('logistics', '0004_remove_packeditem_batch_and_more'),
        ('manufacturing', '0004_remove_batch_current_process_step_remove_batch_mo_and_more'),
        ('quality', '0003_remove_qualitycheck_batch_process_and_more'),
        ('resources', '0003_remove_machineschedule_batch_process_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchProcessExecution',
        ),
    ]
