# Generated by Django 5.2.6 on 2025-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_add_sheet_requirements_to_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='sheets_required',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='total_pieces_from_sheets',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='strips_required',
            field=models.PositiveIntegerField(blank=True, help_text='Number of strips required for this MO (for press components)', null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='total_pieces_from_strips',
            field=models.PositiveIntegerField(blank=True, help_text='Total pieces that will be produced from strips', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='excess_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Excess pieces due to strip constraints', null=True),
        ),
    ]
