# Generated by Django 5.2.6 on 2025-09-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_delete_batch_delete_batchprocessexecution'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sequence_order', models.IntegerField(help_text='Order of execution for this MO')),
                ('planned_start_time', models.DateTimeField(blank=True, null=True)),
                ('planned_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_process_executions', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to='manufacturing.manufacturingorder')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'ordering': ['mo', 'sequence_order'],
                'unique_together': {('mo', 'process')},
            },
        ),
        migrations.CreateModel(
            name='MOProcessStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('rework_required', 'Rework Required')], default='pending', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('quantity_processed', models.PositiveIntegerField(default=0)),
                ('quantity_passed', models.PositiveIntegerField(default=0)),
                ('quantity_failed', models.PositiveIntegerField(default=0)),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operator_notes', models.TextField(blank=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_step_executions', to=settings.AUTH_USER_MODEL)),
                ('process_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='manufacturing.moprocessexecution')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.processstep')),
            ],
            options={
                'ordering': ['process_execution', 'process_step__sequence_order'],
                'unique_together': {('process_execution', 'process_step')},
            },
        ),
        migrations.CreateModel(
            name='MOProcessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('delay', 'Process Delay'), ('quality_issue', 'Quality Issue'), ('equipment_failure', 'Equipment Failure'), ('material_shortage', 'Material Shortage'), ('operator_issue', 'Operator Issue'), ('custom', 'Custom Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('process_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='manufacturing.moprocessexecution')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='manufacturing.moprocessstepexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
