# Generated by Django 5.2.6 on 2025-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_update_sheet_requirements_to_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='scrap_rm_weight',
            field=models.PositiveIntegerField(default=0, help_text='Raw material weight sent to scrap (in grams)'),
        ),
    ]
