# Generated by Django 5.2.6 on 2025-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_batch_scrap_rm_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='scrap_rm_weight',
            field=models.PositiveIntegerField(default=0, help_text='Raw material weight sent to scrap for this MO (in grams)'),
        ),
    ]
