# Generated by Django 5.2.6 on 2025-09-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_moprocessexecution_moprocessstepexecution_and_more'),
        ('processes', '0002_alter_bom_material'),
        ('products', '0003_product_finishing_product_grade_product_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('planned_quantity', models.PositiveIntegerField(help_text='Planned quantity for this batch')),
                ('actual_quantity_started', models.PositiveIntegerField(default=0, help_text='Actual quantity that started production')),
                ('actual_quantity_completed', models.PositiveIntegerField(default=0, help_text='Actual quantity completed successfully')),
                ('scrap_quantity', models.PositiveIntegerField(default=0, help_text='Quantity scrapped during production')),
                ('planned_start_date', models.DateTimeField(blank=True, help_text='Planned start date for this batch', null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, help_text='Planned completion date for this batch', null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, help_text='Actual start date', null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, help_text='Actual completion date', null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('rm_allocated', 'Raw Material Allocated'), ('in_process', 'In Process'), ('quality_check', 'Quality Check'), ('completed', 'Completed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall completion percentage', max_digits=5)),
                ('total_processing_time_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent in processing')),
                ('notes', models.TextField(blank=True, help_text='Any special notes or instructions for this batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, help_text='Primary operator assigned to this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to=settings.AUTH_USER_MODEL)),
                ('assigned_supervisor', models.ForeignKey(blank=True, help_text='Supervisor overseeing this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('current_process_step', models.ForeignKey(blank=True, help_text='Current process step being executed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.processstep')),
                ('mo', models.ForeignKey(help_text='Parent Manufacturing Order', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='manufacturing.manufacturingorder')),
                ('product_code', models.ForeignKey(help_text='Product being manufactured in this batch (should match MO product)', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Production Batch',
                'verbose_name_plural': 'Production Batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mo', 'status'], name='manufacturi_mo_id_0b5851_idx'), models.Index(fields=['product_code', 'status'], name='manufacturi_product_269351_idx'), models.Index(fields=['batch_id'], name='manufacturi_batch_i_a27c18_idx')],
            },
        ),
    ]
