# Generated by Django 5.2.6 on 2025-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('mo_approved', 'MO Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20),
        ),
    ]
