# Generated by Django 5.2.6 on 2025-10-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_manufacturingorder_scrap_rm_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moprocessexecution',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor assigned to this specific process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_process_executions', to=settings.AUTH_USER_MODEL),
        ),
    ]
