# Generated by Django 5.2.6 on 2025-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_moprocessexecution_assigned_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='gst_no_auto',
            field=models.CharField(blank=True, help_text='Auto-filled from vendor', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='mob_no_auto',
            field=models.CharField(blank=True, help_text='Auto-filled from vendor', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_address_auto',
            field=models.TextField(blank=True, help_text='Auto-filled from vendor', null=True),
        ),
    ]
