# Generated by Django 5.2.6 on 2025-09-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_alter_manufacturingorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='customer_order_reference',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name', max_length=200),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor allocates operator (assigned later)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='shift',
            field=models.CharField(blank=True, choices=[('I', '9AM-5PM'), ('II', '5PM-2AM'), ('III', '2AM-9AM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('mo_approved', 'MO Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='on_hold', max_length=20),
        ),
    ]
