# Generated by Django 5.2.6 on 2025-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_alter_purchaseorder_gst_no_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='finishing_auto',
            field=models.CharField(blank=True, help_text='Auto-filled finishing', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='manufacturer_brand_auto',
            field=models.CharField(blank=True, help_text='Auto-filled manufacturer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sheet_roll_auto',
            field=models.CharField(blank=True, help_text='Auto-filled sheet/roll info', max_length=50, null=True),
        ),
    ]
