# Generated by Django 5.2.6 on 2025-10-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_alter_purchaseorder_finishing_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('po_initiated', 'Purchase Order Created'), ('po_approved', 'Approved by GM'), ('po_cancelled', 'Cancelled by Manager'), ('rm_pending', 'Awaiting RM Store Manager Action'), ('rm_completed', 'Goods Receipt Completed')], default='po_initiated', max_length=20),
        ),
    ]
