# Generated by Django 5.2.6 on 2025-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('po_initiated', 'Purchase Order Initiated'), ('po_approved', 'Approved by GM'), ('po_cancelled', 'Cancelled by Manager'), ('rm_pending', 'Awaiting RM Store Manager Action'), ('rm_completed', 'Goods Receipt Completed')], default='po_initiated', max_length=20),
        ),
    ]
