# Generated by Django 5.2.6 on 2025-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, help_text='Actual quantity received (set when GRM is created)', null=True),
        ),
    ]
