# Generated by Django 5.2.6 on 2025-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_purchaseorder_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, help_text='Quantity to order (in kg for coil, sheets for sheet material)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity received (set when GRM is created)', max_digits=10, null=True),
        ),
    ]
