# Generated by Django 5.2.6 on 2025-10-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_alter_purchaseorder_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='assigned_supervisor',
        ),
    ]
