# Generated by Django 5.2.6 on 2025-10-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_remove_supervisor_from_mo'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('returned', 'Returned'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('vendor_contact_person', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_outsourcing_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outsourcing_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsourcing_requests', to='third_party.vendor')),
            ],
            options={
                'verbose_name': 'Outsourcing Request',
                'verbose_name_plural': 'Outsourcing Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutsourcedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_number', models.CharField(help_text='Manufacturing Order number', max_length=20)),
                ('product_code', models.CharField(help_text='Product code', max_length=120)),
                ('qty', models.PositiveIntegerField(blank=True, help_text='Quantity in pieces', null=True)),
                ('kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg', max_digits=10, null=True)),
                ('returned_qty', models.PositiveIntegerField(default=0, help_text='Returned quantity in pieces')),
                ('returned_kg', models.DecimalField(decimal_places=3, default=0, help_text='Returned weight in kg', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.outsourcingrequest')),
            ],
            options={
                'verbose_name': 'Outsourced Item',
                'verbose_name_plural': 'Outsourced Items',
                'ordering': ['mo_number', 'product_code'],
            },
        ),
        migrations.AddIndex(
            model_name='outsourcingrequest',
            index=models.Index(fields=['status'], name='manufacturi_status_98f4de_idx'),
        ),
        migrations.AddIndex(
            model_name='outsourcingrequest',
            index=models.Index(fields=['vendor'], name='manufacturi_vendor__af045a_idx'),
        ),
        migrations.AddIndex(
            model_name='outsourcingrequest',
            index=models.Index(fields=['created_by'], name='manufacturi_created_e9413d_idx'),
        ),
        migrations.AddIndex(
            model_name='outsourcingrequest',
            index=models.Index(fields=['expected_return_date'], name='manufacturi_expecte_748217_idx'),
        ),
        migrations.AddIndex(
            model_name='outsourceditem',
            index=models.Index(fields=['request', 'mo_number'], name='manufacturi_request_332002_idx'),
        ),
        migrations.AddIndex(
            model_name='outsourceditem',
            index=models.Index(fields=['product_code'], name='manufacturi_product_d5c2b9_idx'),
        ),
    ]
