# Generated by Django 5.2.6 on 2025-10-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_add_outsourcing_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='assigned_rm_store',
        ),
    ]
