# Generated by Django 5.2.6 on 2025-10-20 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_missing_handover_fields'),
        ('manufacturing', '0017_remove_assigned_rm_store'),
        ('processes', '0002_add_work_center_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('in_transit', 'In Transit'), ('received', 'Received by Process'), ('in_process', 'In Process'), ('completed', 'Completed'), ('returned', 'Returned to RM Store')], default='allocated', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('location_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_allocations', to=settings.AUTH_USER_MODEL)),
                ('allocated_to_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_batches', to=settings.AUTH_USER_MODEL)),
                ('allocated_to_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='processes.process')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='manufacturing.batch')),
                ('heat_numbers', models.ManyToManyField(blank=True, help_text='Heat numbers allocated to this batch', related_name='batch_allocations', to='inventory.heatnumber')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batch_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Allocation',
                'verbose_name_plural': 'Batch Allocations',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('quality_check_passed', 'Quality Check Passed'), ('quality_check_failed', 'Quality Check Failed'), ('approved_for_dispatch', 'Approved for Dispatch'), ('dispatched', 'Dispatched')], default='pending_verification', max_length=30)),
                ('quality_checked_at', models.DateTimeField(blank=True, null=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fg_verification', to='manufacturing.batch')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_batches', to=settings.AUTH_USER_MODEL)),
                ('quality_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_batches', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fg_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finished Goods Verification',
                'verbose_name_plural': 'Finished Goods Verifications',
            },
        ),
        migrations.CreateModel(
            name='MOApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_manager_approval', 'Pending Manager Approval'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('rm_allocation_pending', 'RM Allocation Pending'), ('rm_allocated', 'RM Allocated'), ('ready_for_production', 'Ready for Production')], default='pending_manager_approval', max_length=30)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_approval_notes', models.TextField(blank=True)),
                ('rm_store_allocated_at', models.DateTimeField(blank=True, null=True)),
                ('rm_allocation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mo_workflows', to=settings.AUTH_USER_MODEL)),
                ('mo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='manufacturing.manufacturingorder')),
                ('rm_store_allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocated_mo_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MO Approval Workflow',
                'verbose_name_plural': 'MO Approval Workflows',
            },
        ),
        migrations.CreateModel(
            name='ProcessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted by Operator'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_notes', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('reassignment_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to=settings.AUTH_USER_MODEL)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_process_assignments', to=settings.AUTH_USER_MODEL)),
                ('mo_process_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_assignments', to='manufacturing.moprocessexecution')),
                ('previous_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_process_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Assignment',
                'verbose_name_plural': 'Process Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Process Started'), ('paused', 'Process Paused'), ('resumed', 'Process Resumed'), ('completed', 'Process Completed'), ('quality_check', 'Quality Check'), ('issue_reported', 'Issue Reported'), ('material_requested', 'Material Requested'), ('tool_change', 'Tool Change'), ('maintenance', 'Maintenance')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quantity_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_status', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('batch_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='manufacturing.batchallocation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Execution Log',
                'verbose_name_plural': 'Process Execution Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
