# Generated by Django 5.2.6 on 2025-10-26 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_increase_transaction_id_length'),
        ('manufacturing', '0018_batchallocation_finishedgoodsverification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity_kg', models.DecimalField(decimal_places=3, help_text='Quantity of raw material allocated in KG', max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('swapped', 'Swapped to Higher Priority MO'), ('locked', 'Locked (MO Approved)'), ('released', 'Released Back to Stock')], default='reserved', max_length=20)),
                ('can_be_swapped', models.BooleanField(default=True, help_text='Can this allocation be swapped to higher priority MO?')),
                ('swapped_at', models.DateTimeField(blank=True, null=True)),
                ('swap_reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When this allocation was locked (MO approved)', null=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocations_locked', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(help_text='Manufacturing Order this allocation is for', on_delete=django.db.models.deletion.CASCADE, related_name='rm_allocations', to='manufacturing.manufacturingorder')),
                ('raw_material', models.ForeignKey(help_text='Raw material being allocated', on_delete=django.db.models.deletion.PROTECT, related_name='mo_allocations', to='inventory.rawmaterial')),
                ('swapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_swaps_performed', to=settings.AUTH_USER_MODEL)),
                ('swapped_to_mo', models.ForeignKey(blank=True, help_text='MO to which this allocation was swapped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocations_received', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'Raw Material Allocation',
                'verbose_name_plural': 'Raw Material Allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (reserved, swapped, locked, released)', max_length=50)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='manufacturing.rawmaterialallocation')),
                ('from_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocation_history_from', to='manufacturing.manufacturingorder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_allocation_history_to', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'RM Allocation History',
                'verbose_name_plural': 'RM Allocation Histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmaterialallocation',
            index=models.Index(fields=['mo', 'status'], name='manufacturi_mo_id_214567_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialallocation',
            index=models.Index(fields=['raw_material', 'status'], name='manufacturi_raw_mat_beaf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialallocation',
            index=models.Index(fields=['can_be_swapped'], name='manufacturi_can_be__bf9c9e_idx'),
        ),
    ]
