# Generated by Django 5.2.6 on 2025-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_rawmaterialallocation_rmallocationhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='shift',
            field=models.CharField(blank=True, choices=[('I', '9AM-5PM (Shift I)'), ('II', '5PM-2AM (Shift II)'), ('III', '2AM-9AM (Shift III)')], max_length=10, null=True),
        ),
    ]
