# Generated by Django 5.2.6 on 2025-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0020_alter_manufacturingorder_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='can_release',
            field=models.BooleanField(default=True, help_text='Whether this batch can be released for production. Set to False when MO is stopped.'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='priority_level',
            field=models.IntegerField(default=0, help_text='Numeric priority level for ordering (higher = more priority). 0=default'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='stop_reason',
            field=models.TextField(blank=True, help_text='Reason for stopping this MO'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='stopped_at',
            field=models.DateTimeField(blank=True, help_text='When this MO was stopped (for resource reallocation)', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rm_allocated', 'RM Allocated'), ('mo_approved', 'MO Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped'), ('on_hold', 'On Hold')], default='on_hold', max_length=20),
        ),
    ]
