# Generated by Django 5.2.6 on 2025-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_batch_can_release_manufacturingorder_priority_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='planned_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
