# Generated by Django 5.2.6 on 2025-10-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_make_planned_dates_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rm_allocated', 'RM Allocated'), ('mo_approved', 'MO Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='on_hold', max_length=20),
        ),
        migrations.CreateModel(
            name='MOTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(help_text='Type of transaction (mo_created, rm_allocated, status_changed, etc.)', max_length=50)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Human-readable description of the transaction')),
                ('details', models.JSONField(default=dict, help_text='Detailed transaction data (stock levels, quantities, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_transactions', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'MO Transaction History',
                'verbose_name_plural': 'MO Transaction Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mo', 'transaction_type'], name='manufacturi_mo_id_8cf98d_idx'), models.Index(fields=['created_at'], name='manufacturi_created_5a2461_idx')],
            },
        ),
        migrations.CreateModel(
            name='POTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(help_text='Type of transaction (po_created, po_approved, grm_received, etc.)', max_length=50)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Human-readable description of the transaction')),
                ('details', models.JSONField(default=dict, help_text='Detailed transaction data (quantities, amounts, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_transactions', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='manufacturing.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Transaction History',
                'verbose_name_plural': 'PO Transaction Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['po', 'transaction_type'], name='manufacturi_po_id_d80c7e_idx'), models.Index(fields=['created_at'], name='manufacturi_created_447094_idx')],
            },
        ),
    ]
