# Generated by Django 5.2.6 on 2025-10-27 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_alter_manufacturingorder_status_motransactionhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_mo_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting this MO'),
        ),
    ]
