# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheckTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_parameters', models.JSONField()),
                ('acceptance_criteria', models.JSONField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_templates', to='processes.processstep')),
            ],
            options={
                'verbose_name': 'Quality Check Template',
                'verbose_name_plural': 'Quality Check Templates',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_values', models.JSONField()),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('rework', 'Rework')], max_length=10)),
                ('check_datetime', models.DateTimeField()),
                ('photos', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.manufacturingorder')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualitychecktemplate')),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Checks',
            },
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_batches', models.JSONField(default=list)),
                ('supplier_lot_numbers', models.JSONField(default=list)),
                ('process_parameters_history', models.JSONField(default=dict)),
                ('operator_history', models.JSONField(default=list)),
                ('machine_history', models.JSONField(default=list)),
                ('quality_results_summary', models.JSONField(default=dict)),
                ('environmental_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'Traceability Record',
                'verbose_name_plural': 'Traceability Records',
            },
        ),
    ]
