# Generated by Django 5.2.6 on 2025-09-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_remove_batch_current_process_step_remove_batch_mo_and_more'),
        ('quality', '0002_auto_20250923_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycheck',
            name='batch_process',
        ),
        migrations.RemoveField(
            model_name='traceabilityrecord',
            name='batch',
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='manufacturing.manufacturingorder'),
        ),
    ]
