# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('total_quantity_ordered', models.PositiveIntegerField(help_text='Total quantity ordered in MO')),
                ('total_quantity_dispatched', models.PositiveIntegerField(default=0, help_text='Total quantity dispatched so far')),
                ('dispatch_date', models.DateTimeField(blank=True, help_text='Planned dispatch date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('partially_dispatched', 'Partially Dispatched'), ('fully_dispatched', 'Fully Dispatched'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for dispatch')),
                ('delivery_address', models.TextField(blank=True, help_text='Delivery address (if different from customer default)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Order',
                'verbose_name_plural': 'Dispatch Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity_dispatched', models.PositiveIntegerField(help_text='Quantity dispatched in this transaction')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of dispatch')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('received', 'Received by Customer'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special instructions')),
                ('delivery_reference', models.CharField(blank=True, help_text='Delivery reference number or tracking ID', max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When dispatch was confirmed', null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='When customer received the dispatch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Transaction',
                'verbose_name_plural': 'Dispatch Transactions',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='FGStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring', 'Expiring Batch'), ('overstock', 'Overstock'), ('custom', 'Custom Alert')], help_text='Type of alert', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('min_stock_level', models.PositiveIntegerField(blank=True, help_text='Minimum stock level threshold', null=True)),
                ('max_stock_level', models.PositiveIntegerField(blank=True, help_text='Maximum stock level threshold', null=True)),
                ('expiry_days_threshold', models.PositiveIntegerField(blank=True, help_text='Days before expiry to trigger alert', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this alert rule active')),
                ('last_triggered', models.DateTimeField(blank=True, help_text='When this alert was last triggered', null=True)),
                ('last_alerted', models.DateTimeField(blank=True, help_text='When notification was last sent', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of this alert rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FG Stock Alert',
                'verbose_name_plural': 'FG Stock Alerts',
                'ordering': ['product_code', 'alert_type'],
            },
        ),
        migrations.CreateModel(
            name='FGStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of FG reserved')),
                ('reservation_type', models.CharField(choices=[('batch_reserve', 'Batch Reserve'), ('customer_reserve', 'Customer Reserve'), ('mo_reserve', 'MO Reserve')], default='mo_reserve', help_text='Type of reservation', max_length=20)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('allocated', 'Allocated'), ('released', 'Released')], default='reserved', help_text='Reservation status', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FG Stock Reservation',
                'verbose_name_plural': 'FG Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity_produced', models.PositiveIntegerField(help_text='Total quantity produced in this batch')),
                ('quantity_packed', models.PositiveIntegerField(default=0, help_text='Quantity packed and ready for dispatch')),
                ('quantity_dispatched', models.PositiveIntegerField(default=0, help_text='Quantity already dispatched')),
                ('loose_stock', models.PositiveIntegerField(default=0, help_text='Individual loose items (not in packs)')),
                ('status', models.CharField(choices=[('pending_dispatch', 'Pending Dispatch'), ('partially_dispatched', 'Partially Dispatched'), ('fully_dispatched', 'Fully Dispatched'), ('cancelled', 'Cancelled')], default='pending_dispatch', max_length=20)),
                ('location_in_store', models.CharField(blank=True, help_text='Physical location in FG store', max_length=100)),
                ('packing_date', models.DateTimeField(blank=True, help_text='Date when batch was packed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch Batch',
                'verbose_name_plural': 'Dispatch Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
