# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fg_store', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchbatch',
            name='mo',
            field=models.ForeignKey(help_text='Parent Manufacturing Order', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_batches', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='dispatchbatch',
            name='packing_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor who packed this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchbatch',
            name='product_code',
            field=models.ForeignKey(help_text='Product being dispatched', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='dispatchbatch',
            name='production_batch',
            field=models.ForeignKey(help_text='Production batch this dispatch batch is based on', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_batch', to='manufacturing.batch'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='customer_c_id',
            field=models.ForeignKey(help_text='Customer for this dispatch', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='third_party.customer', to_field='c_id'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='mo',
            field=models.ForeignKey(help_text='Manufacturing Order for this dispatch', on_delete=django.db.models.deletion.PROTECT, related_name='fg_dispatch_orders', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='dispatchtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchtransaction',
            name='customer_c_id',
            field=models.ForeignKey(help_text='Customer receiving the dispatch', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_transactions', to='third_party.customer', to_field='c_id'),
        ),
        migrations.AddField(
            model_name='dispatchtransaction',
            name='dispatch_batch',
            field=models.ForeignKey(help_text='Dispatch batch being dispatched', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_transactions', to='fg_store.dispatchbatch'),
        ),
        migrations.AddField(
            model_name='dispatchtransaction',
            name='mo',
            field=models.ForeignKey(help_text='Manufacturing Order being dispatched', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_transactions', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='dispatchtransaction',
            name='supervisor_id',
            field=models.ForeignKey(help_text='Supervisor who confirmed the dispatch', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fgstockalert',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fgstockalert',
            name='product_code',
            field=models.ForeignKey(help_text='Product for this alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='fgstockreservation',
            name='mo',
            field=models.ForeignKey(help_text='Manufacturing Order this reservation is for', on_delete=django.db.models.deletion.CASCADE, related_name='fg_reservations', to='manufacturing.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='fgstockreservation',
            name='product_code',
            field=models.ForeignKey(help_text='Product being reserved', on_delete=django.db.models.deletion.PROTECT, related_name='fg_reservations', to='products.product'),
        ),
        migrations.AddField(
            model_name='fgstockreservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispatchbatch',
            index=models.Index(fields=['mo', 'status'], name='fg_store_di_mo_id_c558d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchbatch',
            index=models.Index(fields=['product_code', 'status'], name='fg_store_di_product_c38497_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchbatch',
            index=models.Index(fields=['batch_id'], name='fg_store_di_batch_i_2bb929_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchbatch',
            index=models.Index(fields=['status'], name='fg_store_di_status_fdca1c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['mo', 'status'], name='fg_store_di_mo_id_d0df4d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['customer_c_id', 'dispatch_date'], name='fg_store_di_custome_299416_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['order_id'], name='fg_store_di_order_i_d97162_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['mo', 'status'], name='fg_store_di_mo_id_eb40c6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['dispatch_batch', 'status'], name='fg_store_di_dispatc_d58734_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['customer_c_id', 'dispatch_date'], name='fg_store_di_custome_63a484_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['supervisor_id', 'dispatch_date'], name='fg_store_di_supervi_32d7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['transaction_id'], name='fg_store_di_transac_19984e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['dispatch_date'], name='fg_store_di_dispatc_7ab3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='fgstockalert',
            index=models.Index(fields=['product_code', 'is_active'], name='fg_store_fg_product_c6d6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fgstockalert',
            index=models.Index(fields=['alert_type', 'is_active'], name='fg_store_fg_alert_t_16a8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fgstockreservation',
            index=models.Index(fields=['mo', 'status'], name='fg_store_fg_mo_id_517164_idx'),
        ),
        migrations.AddIndex(
            model_name='fgstockreservation',
            index=models.Index(fields=['product_code', 'status'], name='fg_store_fg_product_825a58_idx'),
        ),
        migrations.AddIndex(
            model_name='fgstockreservation',
            index=models.Index(fields=['reservation_id'], name='fg_store_fg_reserva_96e66a_idx'),
        ),
    ]
