# Generated by Django 5.2.6 on 2025-10-26 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_store', '0001_initial'),
        ('manufacturing', '0021_batch_can_release_manufacturingorder_priority_level_and_more'),
        ('products', '0005_alter_product_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FGStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of FG reserved')),
                ('reservation_type', models.CharField(choices=[('batch_reserve', 'Batch Reserve'), ('customer_reserve', 'Customer Reserve'), ('mo_reserve', 'MO Reserve')], default='mo_reserve', help_text='Type of reservation', max_length=20)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('allocated', 'Allocated'), ('released', 'Released')], default='reserved', help_text='Reservation status', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mo', models.ForeignKey(help_text='Manufacturing Order this reservation is for', on_delete=django.db.models.deletion.CASCADE, related_name='fg_reservations', to='manufacturing.manufacturingorder')),
                ('product_code', models.ForeignKey(help_text='Product being reserved', on_delete=django.db.models.deletion.PROTECT, related_name='fg_reservations', to='products.product')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_reservations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FG Stock Reservation',
                'verbose_name_plural': 'FG Stock Reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mo', 'status'], name='fg_store_fg_mo_id_517164_idx'), models.Index(fields=['product_code', 'status'], name='fg_store_fg_product_825a58_idx'), models.Index(fields=['reservation_id'], name='fg_store_fg_reserva_96e66a_idx')],
            },
        ),
    ]
