# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('supervisor_assigned', 'Supervisor Assigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('variables', models.JSONField(default=list, help_text="List of available variables for this template (e.g., ['mo_id', 'product_name', 'operator_name'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_condition', models.JSONField()),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('delay', 'Process Delay'), ('quality_fail', 'Quality Failure'), ('machine_down', 'Machine Breakdown'), ('custom', 'Custom Rule')], max_length=20)),
                ('notification_methods', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_roles', models.ManyToManyField(related_name='alert_rules', to='authentication.role')),
                ('recipient_users', models.ManyToManyField(blank=True, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('related_object_type', models.CharField(blank=True, max_length=20, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='notifications.alertrule')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notifications.alert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('supervisor_assigned', 'Supervisor Assigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.batch')),
                ('related_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.manufacturingorder')),
                ('related_process_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.processassignment')),
            ],
            options={
                'verbose_name': 'Workflow Notification',
                'verbose_name_plural': 'Workflow Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_631e84_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_998818_idx'), models.Index(fields=['created_at'], name='notificatio_created_378a16_idx')],
            },
        ),
    ]
