# Generated by Django 5.2.6 on 2025-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('supervisor_assigned', 'Supervisor Assigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch'), ('patrol_duty_assigned', 'Patrol Duty Assigned'), ('patrol_duty_ending_soon', 'Patrol Duty Ending Soon')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='notification_type',
            field=models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('supervisor_assigned', 'Supervisor Assigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch'), ('patrol_duty_assigned', 'Patrol Duty Assigned'), ('patrol_duty_ending_soon', 'Patrol Duty Ending Soon')], max_length=30),
        ),
    ]
