# Generated by Django 5.2.6 on 2025-10-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mo_created', 'Manufacturing Order Created'), ('po_created', 'Purchase Order Created'), ('mo_approved', 'Manufacturing Order Approved'), ('po_approved', 'Purchase Order Approved'), ('mo_cancelled', 'Manufacturing Order Cancelled'), ('po_cancelled', 'Purchase Order Cancelled')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_type', models.CharField(max_length=10)),
                ('related_id', models.IntegerField()),
                ('related_code', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Notification',
                'verbose_name_plural': 'Manager Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
