# Generated by Django 5.2.6 on 2025-10-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_managernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerNotification',
        ),
    ]
