# Generated by Django 5.2.6 on 2025-10-20 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_batchallocation_finishedgoodsverification_and_more'),
        ('notifications', '0003_delete_managernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('variables', models.JSONField(default=list, help_text="List of available variables for this template (e.g., ['mo_id', 'product_name', 'operator_name'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mo_created', 'MO Created'), ('mo_approved', 'MO Approved'), ('mo_rejected', 'MO Rejected'), ('rm_allocation_required', 'RM Allocation Required'), ('rm_allocated', 'RM Allocated'), ('process_assigned', 'Process Assigned'), ('process_reassigned', 'Process Reassigned'), ('batch_allocated', 'Batch Allocated'), ('batch_received', 'Batch Received'), ('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('quality_check_required', 'Quality Check Required'), ('fg_verification_required', 'FG Verification Required'), ('ready_for_dispatch', 'Ready for Dispatch')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.batch')),
                ('related_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.manufacturingorder')),
                ('related_process_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manufacturing.processassignment')),
            ],
            options={
                'verbose_name': 'Workflow Notification',
                'verbose_name_plural': 'Workflow Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_631e84_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_998818_idx'), models.Index(fields=['created_at'], name='notificatio_created_378a16_idx')],
            },
        ),
    ]
