# Generated by Django 5.2.6 on 2025-10-04 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=50)),
                ('capacity_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('breakdown', 'Breakdown')], default='available', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supported_processes', models.ManyToManyField(related_name='compatible_machines', to='processes.processstep')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='MachineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='resources.machine')),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'Machine Schedule',
                'verbose_name_plural': 'Machine Schedules',
            },
        ),
    ]
