# Generated by Django 5.2.6 on 2025-09-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
    ]
