# Generated by Django 5.2.6 on 2025-11-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=120, unique=True)),
                ('product_type', models.CharField(choices=[('spring', 'Spring'), ('press_component', 'PRESS COMPONENT'), ('stamp', 'Stamp')], default='spring', max_length=20)),
                ('spring_type', models.CharField(choices=[('tension', 'TENSION SPRING'), ('wire_form', 'WIRE FORM SPRING'), ('compression', 'COMPRESSION SPRING'), ('torsion', 'TORSION SPRING'), ('clip', 'CLIP'), ('rivet', 'RIVET'), ('helical', 'HELICAL SPRING'), ('length_pin', 'LENGTH PIN'), ('length_rod', 'LENGTH ROD'), ('double_torsion', 'DOUBLE TORSION SPRING'), ('cotter_pin', 'COTTER PIN'), ('conical', 'CONICAL SPRING'), ('ring', 'RING'), ('s-spring', 'S-SPRING')], default='tension', max_length=20)),
                ('grams_per_product', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams per single product unit (used for RM calculation)', max_digits=10, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Length in mm (for press components/sheet materials)', max_digits=10, null=True)),
                ('breadth_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Breadth in mm (for press components/sheet materials)', max_digits=10, null=True)),
                ('whole_sheet_length_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Standard sheet length we purchase (L) in mm', max_digits=10, null=True)),
                ('whole_sheet_breadth_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Standard sheet breadth we purchase (B) in mm', max_digits=10, null=True)),
                ('strip_length_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Strip length cut from sheet (L) in mm', max_digits=10, null=True)),
                ('strip_breadth_mm', models.DecimalField(blank=True, decimal_places=3, help_text='Strip breadth cut from sheet (B) in mm', max_digits=10, null=True)),
                ('strips_per_sheet', models.PositiveIntegerField(blank=True, help_text='How many strips come from one full sheet (for RM ordering calculation)', null=True)),
                ('pcs_per_strip', models.PositiveIntegerField(blank=True, help_text='Number of finished parts per strip', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_product_code', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('customer_c_id', models.ForeignKey(blank=True, help_text='Customer associated with this product (references c_id)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='third_party.customer', to_field='c_id')),
                ('material', models.ForeignKey(help_text='Raw material used for this product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
