# Generated by Django 5.2.6 on 2025-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Breadth in mm (for press components/sheet materials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grams_per_product',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams per single product unit (used for RM calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Length in mm (for press components/sheet materials)', max_digits=10, null=True),
        ),
    ]
