# Generated by Django 5.2.6 on 2025-09-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250923_0835'),
    ]

    operations = [
        # Empty migration to satisfy manufacturing app dependency
        # The current Product model already has all required fields
    ]
