# Generated by Django 5.2.6 on 2025-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250923_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finishing',
            field=models.CharField(blank=True, help_text='Surface finishing', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, help_text='Material grade', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_brand',
            field=models.CharField(blank=True, help_text='Manufacturer/Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material_name',
            field=models.CharField(blank=True, help_text='Material name/type', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='part_name',
            field=models.CharField(blank=True, help_text='Descriptive name of the part', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, help_text='Part number for identification', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('spring', 'Spring'), ('stamping_part', 'Stamping Part')], default='spring', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rm_consumption_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Raw material consumption per unit (kg)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard cost per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Thickness for sheet materials', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wire_diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Wire diameter for coil materials', max_digits=8, null=True),
        ),
    ]
