# Generated by Django 5.2.6 on 2025-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcs_per_sheet',
            field=models.PositiveIntegerField(blank=True, help_text='Total parts from one full sheet = Strip Count × Pcs per Strip (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pcs_per_strip',
            field=models.PositiveIntegerField(blank=True, help_text='Number of finished parts per strip', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='process_1',
            field=models.CharField(blank=True, help_text='First process step (e.g., Piercing & Parting)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_2',
            field=models.CharField(blank=True, help_text='Second process step (e.g., Deburring)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_3',
            field=models.CharField(blank=True, help_text='Third process step (e.g., Ironing)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_4',
            field=models.CharField(blank=True, help_text='Fourth process step', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_5',
            field=models.CharField(blank=True, help_text='Fifth process step', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_6',
            field=models.CharField(blank=True, help_text='Sixth process step', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='process_7',
            field=models.CharField(blank=True, help_text='Seventh process step', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='strip_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Strip breadth cut from sheet (B) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='strip_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many strips come from one full sheet', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='strip_length_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Strip length cut from sheet (L) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='whole_sheet_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Standard sheet breadth we purchase (B) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='whole_sheet_length_mm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Standard sheet length we purchase (L) in mm', max_digits=10, null=True),
        ),
    ]
