# Generated by Django 5.2.6 on 2025-10-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_finishing_product_grade_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_product_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spring_type',
            field=models.CharField(choices=[('tension', 'TENSION SPRING'), ('wire_form', 'WIRE FORM SPRING'), ('compression', 'COMPRESSION SPRING'), ('torsion', 'TORSION SPRING'), ('clip', 'CLIP'), ('rivet', 'RIVET'), ('helical', 'HELICAL SPRING'), ('length_pin', 'LENGTH PIN'), ('length_rod', 'LENGTH ROD'), ('double_torsion', 'DOUBLE TORSION SPRING'), ('cotter_pin', 'COTTER PIN'), ('conical', 'CONICAL SPRING'), ('ring', 'RING'), ('s-spring', 'S-SPRING')], default='tension', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('spring', 'Spring'), ('press_component', 'PRESS COMPONENT')], default='spring', max_length=20),
        ),
    ]
