# Generated by Django 5.2.6 on 2025-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_sheet_calculation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcs_per_sheet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='strip_count',
        ),
        migrations.AddField(
            model_name='product',
            name='strips_per_sheet',
            field=models.PositiveIntegerField(blank=True, help_text='How many strips come from one full sheet (for RM ordering calculation)', null=True),
        ),
    ]
