# Generated by Django 5.2.6 on 2025-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_update_sheet_calculation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('spring', 'Spring'), ('press_component', 'PRESS COMPONENT'), ('stamp', 'Stamp')], default='spring', max_length=20),
        ),
    ]
