# Generated by Django 5.2.6 on 2025-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_internal_product_code_product_spring_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_product_code',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
