# Generated by Django 5.2.6 on 2025-10-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_internal_product_code'),
        ('third_party', '0006_alter_customer_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='third_party.customer'),
        ),
    ]
